server {
    listen 5000;

    # Serve static files
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Proxy /query/ requests to catalog1
    location /query/ {
        proxy_pass http://catalog1:5001/info/;
    }

    # Proxy /search/ requests to catalog1
    location /search/ {
        proxy_pass http://catalog1:5001/search/;
    }
}
